# Generated by Django 5.1.4 on 2026-08-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='예: 작업대 보호장치', max_length=100, verbose_name='장치명')),
                ('lead', models.CharField(help_text='이 장치가 무엇을 막아주는지 한 문장으로.', max_length=200, verbose_name='설명')),
                ('note', models.CharField(blank=True, help_text='선택. 예: 철망/메쉬망 및 함석 부착 예시', max_length=200, verbose_name='보조 문구')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
            ],
            options={
                'verbose_name': '옵션 장치',
                'verbose_name_plural': '옵션 장치',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OptionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_label', models.CharField(help_text='같은 칸에 넣을 사진은 이름을 똑같이 적으세요. 예: 철망/메쉬망 보양', max_length=100, verbose_name='칸 이름')),
                ('column_tag', models.CharField(blank=True, help_text='선택. 예: 장착 A type — 칸의 첫 사진 값만 쓰입니다.', max_length=50, verbose_name='칸 위 작은 라벨')),
                ('image', models.ImageField(upload_to='options/', verbose_name='사진')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='options.optiondevice', verbose_name='옵션 장치')),
            ],
            options={
                'verbose_name': '옵션 장치 사진',
                'verbose_name_plural': '옵션 장치 사진',
                'ordering': ['order', 'id'],
            },
        ),
    ]
