# Generated by Django 5.1.4 on 2026-08-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionphoto',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='optionphoto',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='optionphoto',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='options/', verbose_name='사진', width_field='image_width'),
        ),
    ]
