# Generated by Django 5.1.4 on 2026-08-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_optionphoto_image_height_optionphoto_image_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionphoto',
            name='caption',
            field=models.CharField(blank=True, help_text='선택. 사진 바로 위에 붙습니다. 예: 자세한 사진', max_length=100, verbose_name='사진 위 설명'),
        ),
    ]
