# Generated by Django 5.1.4 on 2026-08-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_optioncolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionphoto',
            name='caption',
            field=models.CharField(blank=True, help_text='선택. 사진 바로 위에 붙습니다. 예: 측면사진', max_length=100, verbose_name='사진 위 설명'),
        ),
        migrations.AlterField(
            model_name='optionphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='한 칸 안에서 위에서 아래 순입니다.', verbose_name='순서'),
        ),
    ]
