# Generated by Django 5.1.4 on 2026-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_alter_optionphoto_caption_alter_optionphoto_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionphoto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='노출 여부'),
        ),
    ]
