# Generated by Django 5.1.4 on 2026-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0006_optionphoto_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionphoto',
            name='image',
            field=models.ImageField(upload_to='options/', verbose_name='사진'),
        ),
    ]
