# Generated by Django 5.1.4 on 2026-04-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='모델명')),
                ('category', models.CharField(choices=[('5m', '5M급'), ('6m', '6M급'), ('7m', '7M급'), ('8m', '8M급'), ('10m', '10M급'), ('12m', '12M급'), ('14m', '14M급'), ('15m_boom', '15M급 굴절형')], max_length=20, verbose_name='미터급')),
                ('type', models.CharField(choices=[('scissor', '시저'), ('boom', '굴절'), ('vertical', '버티칼'), ('other', '기타')], max_length=20, verbose_name='타입')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='장비 사진')),
                ('description', models.TextField(blank=True, verbose_name='장비 설명')),
                ('max_work_height', models.CharField(max_length=50, verbose_name='작업가능높이')),
                ('max_platform_height', models.CharField(max_length=50, verbose_name='발판최대높이')),
                ('equipment_weight', models.CharField(max_length=50, verbose_name='장비무게')),
                ('max_load', models.CharField(max_length=50, verbose_name='적재가능중량')),
                ('equipment_size', models.CharField(max_length=100, verbose_name='장비크기')),
                ('platform_size', models.CharField(max_length=100, verbose_name='작업대크기')),
                ('power_type', models.CharField(max_length=50, verbose_name='동력')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '장비',
                'verbose_name_plural': '장비 목록',
                'ordering': ['category', 'name'],
            },
        ),
    ]
