# Generated by Django 5.1.4 on 2026-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='판매 가능'),
        ),
    ]
