# Generated by Django 5.1.4 on 2026-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_is_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='daangn_url',
            field=models.URLField(blank=True, verbose_name='당근마켓 URL'),
        ),
    ]
