# Generated by Django 5.1.4 on 2026-05-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_daangn_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='daangn_url',
        ),
    ]
