# Generated by Django 5.1.4 on 2026-05-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipment_daangn_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='이미지')),
                ('image_type', models.CharField(choices=[('rental', '렌탈용'), ('sales', '판매용')], max_length=10, verbose_name='이미지 용도')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment', verbose_name='장비')),
            ],
            options={
                'verbose_name': '장비 이미지',
                'verbose_name_plural': '장비 이미지 목록',
                'ordering': ['order'],
            },
        ),
    ]
