# Generated by Django 5.1.4 on 2026-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('5m', '5M급'), ('6m', '6M급'), ('7m', '7M급'), ('8m', '8M급'), ('10m', '10M급'), ('12m', '12M급'), ('14m', '14M급')], max_length=20, verbose_name='미터급'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image_type',
            field=models.CharField(choices=[('rental', '렌탈용'), ('sales', '판매용'), ('compare', '비교용')], max_length=10, verbose_name='이미지 용도'),
        ),
    ]
