# Generated by Django 5.1.4 on 2026-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_flagship',
            field=models.BooleanField(default=False, verbose_name='대표장비'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_for_rent',
            field=models.BooleanField(default=True, verbose_name='렌탈 노출'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('5m', '1인승'), ('6m', '미니'), ('7m', '7M급'), ('8m', '8M급'), ('10m', '10M급'), ('12m', '12M급'), ('14m', '14M급'), ('etc', '기타장비')], max_length=20, verbose_name='미터급'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='판매 노출'),
        ),
    ]
