# Generated by Django 5.1.4 on 2026-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentimage',
            name='baseline',
            field=models.FloatField(blank=True, help_text='사진 맨 아래에서 바퀴가 땅에 닿는 지점까지의 높이 비율(%). 비워두면 자동으로 계산한 값을 사용합니다. 비교 페이지에서 이 장비의 바퀴 높이가 어긋나 보일 때만 입력하세요.', null=True, verbose_name='바퀴선 위치(%)'),
        ),
    ]
