# Generated by Django 5.1.4 on 2026-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_equipmentimage_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('5m', '1인승'), ('6m', '미니(6M급)'), ('7m', '7M급'), ('8m', '8M급'), ('10m', '10M급'), ('12m', '12M급'), ('14m', '14M급'), ('16m', '16M급'), ('etc', '기타장비')], max_length=20, verbose_name='미터급'),
        ),
    ]
