# Generated by Django 5.1.4 on 2026-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={'ordering': ['order'], 'verbose_name': '장비 사진', 'verbose_name_plural': '장비 사진'},
        ),
        migrations.AddField(
            model_name='equipmentimage',
            name='baseline_detected',
            field=models.FloatField(blank=True, help_text='사진을 올리면 시스템이 바퀴가 땅에 닿는 위치를 자동으로 찾아 채웁니다. 직접 고칠 필요는 없습니다.', null=True, verbose_name='바퀴선 자동 인식값(%)'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='baseline',
            field=models.FloatField(blank=True, help_text='비워두면 위의 자동 인식값을 사용합니다. 장비 비교 페이지에서 이 장비만 바퀴 높이가 어긋나 보일 때에만 숫자를 입력하세요. (사진 맨 아래에서 바퀴까지의 높이 비율, 예: 4.2)', null=True, verbose_name='바퀴선 직접 지정(%)'),
        ),
    ]
