# Generated by Django 5.1.4 on 2026-08-06 18:00

from django.db import migrations, models

# The machine that rents most today. Seeded here so the landing page is right
# the moment this deploys; from then on it is an admin checkbox and this
# migration must not be re-run or edited to chase it.
INITIAL_BESTSELLER = 'SJ3219'


def set_initial_bestseller(apps, schema_editor):
    Equipment = apps.get_model('equipment', 'Equipment')
    Equipment.objects.filter(name=INITIAL_BESTSELLER).update(is_bestseller=True)


def clear_bestseller(apps, schema_editor):
    Equipment = apps.get_model('equipment', 'Equipment')
    Equipment.objects.update(is_bestseller=False)


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_equipmentimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='랜딩 페이지 "많이 찾는 장비" 목록 맨 앞에 나옵니다. 보통 한 대만 체크합니다.', verbose_name='최다 문의 장비'),
        ),
        migrations.RunPython(set_initial_bestseller, clear_bestseller),
    ]
