# Generated by Django 5.1.4 on 2026-08-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_equipment_is_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='is_bestseller',
        ),
    ]
