# Generated by Django 5.1.4 on 2026-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_remove_equipment_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='노출 여부'),
        ),
    ]
