# Generated by Django 5.1.4 on 2026-07-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='모델명')),
                ('shipped_date', models.DateField(verbose_name='출고일')),
                ('photo_key', models.PositiveIntegerField(blank=True, help_text='static/images/records/<ID>/ 폴더 번호 (임포트 데이터용)', null=True, unique=True, verbose_name='사진 폴더 ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '판매 실적',
                'verbose_name_plural': '판매 실적 목록',
                'ordering': ['-shipped_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='records/', verbose_name='사진')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='records.salesrecord', verbose_name='실적')),
            ],
            options={
                'verbose_name': '실적 사진',
                'verbose_name_plural': '실적 사진 목록',
                'ordering': ['order'],
            },
        ),
    ]
