# Generated by Django 5.1.4 on 2026-08-22 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_delete_salesrecordimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='shipped_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='출고일'),
        ),
    ]
