# Generated by Django 5.1.4 on 2026-04-07 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('name', models.CharField(max_length=100, verbose_name='담당자명')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('business_number', models.CharField(blank=True, max_length=20, verbose_name='사업자번호')),
                ('start_date', models.DateField(verbose_name='렌탈 시작일')),
                ('end_date', models.DateField(verbose_name='렌탈 종료일')),
                ('delivery_address', models.TextField(verbose_name='배송지 주소')),
                ('budget', models.PositiveIntegerField(blank=True, null=True, verbose_name='예산')),
                ('message', models.TextField(blank=True, verbose_name='추가 요청사항')),
                ('status', models.CharField(choices=[('pending', '대기'), ('reviewing', '검토중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
            ],
            options={
                'verbose_name': '견적 신청',
                'verbose_name_plural': '견적 신청 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='장비')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quoterequest', verbose_name='견적')),
            ],
            options={
                'verbose_name': '견적 장비',
                'verbose_name_plural': '견적 장비 목록',
            },
        ),
    ]
