# Generated by Django 5.1.4 on 2026-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('message', models.TextField(blank=True, verbose_name='문의 내용')),
                ('is_called', models.BooleanField(default=False, verbose_name='전화 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
            ],
            options={
                'verbose_name': '콜백 신청',
                'verbose_name_plural': '콜백 신청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
