# Generated by Django 5.1.4 on 2026-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='inquiry_type',
            field=models.CharField(blank=True, choices=[('rental', '렌탈'), ('sale', '판매'), ('undecided', '미정')], default='rental', max_length=20, verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='work_height_class',
            field=models.CharField(blank=True, max_length=20, verbose_name='필요 작업고'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='현장 주소'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='렌탈 종료일'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='담당자명'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='렌탈 시작일'),
        ),
    ]
