# Generated by Django 5.1.4 on 2026-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quoterequest_inquiry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='privacy_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='개인정보 수집·이용 동의일시'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='privacy_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='개인정보 수집·이용 동의일시'),
        ),
    ]
