# Generated by Django 5.1.4 on 2026-08-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_callbackrequest_privacy_agreed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(verbose_name='갱신 토큰')),
                ('access_token', models.TextField(blank=True, verbose_name='접속 토큰')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='접속 토큰 만료')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='연결된 카카오 계정')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 발송')),
                ('last_error', models.TextField(blank=True, verbose_name='마지막 오류')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '카카오톡 알림 연결',
                'verbose_name_plural': '카카오톡 알림 연결',
            },
        ),
    ]
